---
parent: Api_v1_issues
name: ApiV1IssuesPutCorsConfig
description: null
authors:
- apisec Bot
type: SUITE
init: []
localVariables: []
path: /api/v1/issues
endpoint: /api/v1/issues
method: PUT
auth: Default
headers:
- 'Accept: application/json'
- 'Content-Type: application/json'
- 'Origin: vulnerable.{{@Host}}'
testCases:
- id: 1
  body: |-
    {
      "assertions" : "{{@Random}}",
      "assignedTo" : "{{@Random}}",
      "createdBy" : "",
      "createdDate" : "",
      "description" : "{{@Random}}",
      "endpoint" : "{{@Random}}",
      "env" : "{{@Random}}",
      "failedAssertions" : "{{@Random}}",
      "headers" : [ "{{@Random}}" ],
      "id" : "",
      "inactive" : false,
      "issueName" : "{{@Random}}",
      "issueStatus" : "CLOSED",
      "issueType" : "AUTOMATIC",
      "method" : "PATCH",
      "modifiedBy" : "",
      "modifiedDate" : "",
      "project" : {
        "createdBy" : "",
        "createdDate" : "",
        "description" : "{{@Random}}",
        "id" : "",
        "inactive" : false,
        "modifiedBy" : "",
        "modifiedDate" : "",
        "name" : "{{@Random}}",
        "org" : {
          "createdBy" : "",
          "createdDate" : "",
          "id" : "",
          "inactive" : false,
          "modifiedBy" : "",
          "modifiedDate" : "",
          "name" : "{{@Random}}",
          "version" : ""
        },
        "refId" : "{{@Random}}",
        "version" : ""
      },
      "requestBody" : "{{@Random}}",
      "responseBody" : "{{@Random}}",
      "responseHeaders" : "{{@Random}}",
      "result" : "{{@Random}}",
      "statusCode" : "{{@Random}}",
      "tags" : [ "{{@Random}}" ],
      "version" : ""
    }
  inactive: false
useCategoryAssertion: false
assertions:
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(\*)(.*)'
- '@ResponseHeaders.Access-Control-Allow-Origin != @NULL'
- '@ResponseHeaders.Access-Control-Allow-Origin !=~ (.*)(vulnerable)(.*)'
cleanup: []
severity: Medium
category: cors_config
tags:
- V1
- Misconfiguration
- OWASP-OriginHeaderScrutiny
- OWASP-API7
inactive: false
policies:
  initExec: Request
  cleanupExec: Request
  logger: DEBUG
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: null
  repeatDelay: 0
  unmaskToken: false
  postExecutionDelay: 0
autoGenerated: true
